### ISSUE TITLE
Usage Question

### ISSUE THREAD

**Issue by jonleopard** [belak/base16-builder-go#26]
Hello!

I used `base16-builder-go` a couple years ago and it worked very nicely. I need to fix/adjust a theme and I'd like to use your tool again. I've removed the old binary from my system and made sure to start from scratch.  I pulled in the latest version of this tool via `go get` and also cloned the `schemes` repo per the instructions. After running `base16-builder-go` without any flags, this is what returns:

```
INFO[0000] base16-builder-go                             commit=unknown date=unknown spec-version=0.10.1 version=dev
INFO[0000] Using internal schemes
WARN[0000] Scheme author should not be empty             file=seti.yaml
INFO[0000] Found 232 color schemes
PANI[0000] open templates/config.yaml: no such file or directory
panic: (*logrus.Entry) 0xc00010f490

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc00010fb20, 0x0, {0xc000371fc0, 0x35})
        /Users/jon/go/src/github.com/sirupsen/logrus/entry.go:260 +0x4a7
github.com/sirupsen/logrus.(*Entry).Log(0xc00010fb20, 0x0, {0xc0000c9c90?, 0x7?, 0xc0000c9ca0?})
        /Users/jon/go/src/github.com/sirupsen/logrus/entry.go:304 +0x4f
github.com/sirupsen/logrus.(*Entry).Panic(...)
        /Users/jon/go/src/github.com/sirupsen/logrus/entry.go:342
main.main()
        /Users/jon/go/src/github.com/base16-project/base16-builder-go/main.go:109 +0x6b4

```

Seems that I am missing a  `templates/config.yaml` file? My memory is a little foggy from the last time I did this, was I supposed to pull in another file for `base16-builder-go` to read from? 

Sorry for the noob-ish question! Any tips you could give on how I can use this tool would be helpful :)

Cheers!

**Comment by belak** [comment]
Hello! Thanks for reaching out! There's a bit more information [in the home repo](https://github.com/base16-project/home/blob/main/builder.md#template-repository), but we're looking at changing that in the future. I'll make sure to update the docs here when that happens.

If you're still having trouble, feel free to push up the code somewhere and I can take a look.
